Django/05_blog_CBV/blog/urls.py
from django.urls import path
from blog import cb_views
from blog import views

app_name = 'blog'

urlpatterns = [
    # CBV blog
    path('', cb_views.BlogListView.as_view(), name = 'list'),
    path('<int:blog_pk>/', cb_views.BlogDetailView.as_view(), name = 'detail'),
    path('create/', cb_views.BlogCreateView.as_view(), name = 'create'),
    path('<int:pk>/update/', cb_views.BlogUpdateView.as_view(), name = 'update'),
    # path('<int:pk>/update/', views.blog_update, name = 'update'), # FBV로 테스트
    path('<int:pk>/delete/', cb_views.BlogDeleteView.as_view(), name = 'delete'),
    path('comment/create/<int:blog_pk>/', cb_views.CommentCreateView.as_view(), name = 'comment-create'),
]

# # url불러올 때 app_name:name
# # html에서 불러오기
# {% url 'blog:detail' blog.pk %}
# {% url 'blog:list' %}
#
# # python에서 불러오기
# reverse_lazy('blog:list')
# redirect(reverse('blog:list'))

# request.user.is_staff
# request.user.is_superuser

Django/05_blog_CBV/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import path, include, reverse
from django.views.generic import TemplateView, RedirectView
from django.views import View
from blog import views as blog_views
from member import views as member_views
from blog import cb_views

def index(reqeust):
    # return redirect('blog/')
    return redirect(reverse('blog:list'))

class AboutView(TemplateView):
    template_name='about.html'

class TestView(View):
    def get(self, request):
        return render(request, 'test_get.html')
    def post(self, request):
        return render(request, 'test_post.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    # include 기능 사용
    # FBV blog
    path('fb/', include('blog.fbv_urls')),  # 경로에 fb/추가됨. # fb/
    # CBV blog
    path('blog/', include('blog.urls')),  # blog/
    # login 기능
    path('accounts/', include('django.contrib.auth.urls')), # include() 장고에 내장된 url사용
    path('signup/', member_views.sign_up, name = 'signup'),
    path('login/', member_views.login, name = 'login'),
    # test
    # path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('about/', AboutView.as_view(), name='about'),
    path('redirect/', RedirectView.as_view(pattern_name='about'), name='redirect'),
    path('redirect2/', lambda req: redirect('about')),
    path('test/', TestView.as_view(), name='test'),
    #summernote
    path('summernote/', include('django_summernote.urls')),
]

# config.settings 보단 django.conf의 settings가 나음.
# 현재 장고 실행환경에서 셋팅을 불러옴.  배포환경에서는 경로가 달라질 수 있기 때문에 이렇게함.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # django.conf.urls.static

Django/05_blog_CBV/blog/models.py
from io import BytesIO
from pathlib import Path

from PIL import Image
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.db import models
from django.urls import reverse
from utils.models import TimestampModel

# from django.contrib.auth.models import User
User = get_user_model()  # 장고에 설정되어있는 유저를 가져오는 함수

# Blog 구조
# 제목
# 본문
# 작성자
# 작성일자
# 수정일자
# 카테고리
# 썸네일이미지 - 미구현
# 태그 - 미구현

class Blog(TimestampModel):
    CATEGORY_CHOICES = (
        ('free','자유'),
        ('travel','여행'),
        ('cat','고양이'),
        ('dog','개'),
    )
    # blog.objects.filter(category__isnull=true) # Null인 데이터 확인
    # Blog.objects.filter(category='')  # 비어있는 데이터 확인
    # Blog.objects.filter(category='').update(category='free')
    category = models.CharField('카테고리', max_length=20, choices=CATEGORY_CHOICES, default='free')
    title = models.CharField('제목', max_length=100)
    content = models.TextField('본문')
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # author_id

    image = models.ImageField('이미지', null=True, blank=True, upload_to='blog/%Y/%m/%d')
    thumbnail = models.ImageField('썸네일', null=True, blank=True, upload_to="blog/%Y/%m/%d/thumbnail")
    # 2024/4/23일
    # blog/2024/4/23/이미지파일.jpg
    # ImageField, FieldField와 같은데 이미지만 업로드하게 되어있다.
    # varchar => 경로만 저장을 함
    # 이미지 필드를 사용하기 위해 pillow설  poetry add pillow

    # models.CASCATE => 같이 삭제 => 유저 삭제시 같이 블로그도 같이 삭제
    # models.PROTECT => 삭제가 불가능함 => 유저를 삭제하려고 할 때 블로그가 있으면 유저 삭제가 불가능 (기본값)
    # models.SET_NULL => 널 값을 넣음 => 유저 삭제시 블로그의 author가 Null이 됨.

    # 기존에 없던 author를 외례키로 추가하면 기존 블로그의 author값이 없어서 마이그레이션 할 때 에러남
    # python3 manage.py makemigrations 하면 기존 블로그 데이터에 기본값을 줄건지 물어봄.
    # 1번 기본값 주기 선택 후 기존 데이터의 초기값으로 주어질 id값 선택 하면 정상적으로 마이그레이션 됨.

    # TimestampModel에서 created_at, updated_at을 상속받음
    # created_at = models.DateTimeField('작성일자', auto_now_add=True)
    # updated_at = models.DateTimeField('수정일자', auto_now_add=True)

    def __str__(self):
        return f'[{self.get_category_display()}] {self.title[:10]}'

    # get_absolute_url은 보통 detail페이지
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'blog_pk':self.pk})

    # 썸네일 이미지 가져오는 함수
    def get_thumbnail_image_url(self):
        if self.thumbnail:
            return self.thumbnail.url
        elif self.image:
            return self.image.url
        return None

    # save()함수 override
    def save(self, *args, **kwargs): # *args 리스트 **kwargs 키워드
        if not self.image:
            return super().save(*args, **kwargs)

        image = Image.open(self.image)
        image.thumbnail((300, 300))
        image_path = Path(self.image.name)
        thumbnail_name = image_path.stem # /blog/2024/4/23/database.png => 파일 이름만 불러옴
        thumbnail_extension = image_path.suffix.lower() # 파일의 확장자를 가져옴 # 소문자로 바꿔서 처리
        thumbnail_filename = f'{thumbnail_name}_thumb{thumbnail_extension}' # 이름_thumb.확장자

        if thumbnail_extension in ['.jpg','jpeg']:
            file_type = 'JPEG'  # jpg일때 처리가 안되서 바꿔서 처리
        elif thumbnail_extension == '.gif':
            file_type = 'GIF'
        elif thumbnail_extension == '.png':
            file_type = 'PNG'
        else:
            return super().save(*args, **kwargs)

        temp_thumb = BytesIO()
        image.save(temp_thumb, file_type)
        temp_thumb.seek(0)
        thumb_file = ContentFile(temp_thumb.read())  # File 타입이 아니라서 생기는 오류 해결
        self.thumbnail.save(thumbnail_filename, thumb_file, save=False)
        temp_thumb.close()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = '블로그'
        verbose_name_plural = '블로그 목록'

# Comment 구조
# blog정보
# 댓글 내용
# 작성자
# 작성일자
# 수정일자
# 카테고리

class Comment(TimestampModel):
    # TimestampModel에서 created_at, updated_at을 상속받음
    # created_at = models.DateTimeField('작성일자', auto_now_add=True)
    # updated_at = models.DateTimeField('수정일자', auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.CharField('본문', max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.blog.title} 댓글'

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글 목록'
        ordering = ('-created_at', '-id',) # 댓글 최신순으로 정렬

Django/05_blog_CBV/blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from blog.models import Blog, Comment

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        # fields = '__all__'  # 전체 적용
        fields = ('category','title', 'image', 'content')  # 원하는 것만 적용, 순서대로 적용됨.
        widgets = {
            'content': SummernoteWidget()
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        # 특정 필드에 TextInput 삽입
        widgets = {
            'content': forms.TextInput(attrs={'class':'form-control'}) # content필드에 textinput 삽입
        }
        # Comment 모델이 가지고있는 verbose_name 쓰지 않고 따로 지정
        labels = {
            'content': '댓글'
        }

Django/05_blog_CBV/blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from blog.forms import BlogForm
from blog.models import Blog

def blog_list(request):
    # order_by('정렬 기준 값') 오름차순(ASC)으로 정렬.  값에 '-'를 붙이면 내림차순(DESC)정렬
    blogs = Blog.objects.all().order_by('-created_at')
    # blogs = Blog.objects.all().order_by('-created_at')[10:21]

    q = request.GET.get('q')
    if q:
        blogs = blogs.filter(Q(title__icontains=q) | Q(content__icontains=q))
        # blogs = blogs.filter(title__icontains=q)

    paginator = Paginator(blogs, 10)  # blogs를 10개 단위로 페이지를 만듬
    page = request.GET.get('page')  # 파라미터 값으로 page값이 들어오면 page값 반환. 0이거나 최대페이지를 초과하는 페이지는 마지막 페이지를 반환. 숫자가 아닌값이 들어오면 첫페이지
    page_object = paginator.get_page(page)  # 해당 페이지로 이동

    # visit을 키값으로 쿠키를 가져오고 존재하지 않으면 0 있으면 +1
    visits = int(request.COOKIES.get('visits', 0 )) + 1

    request.session['count'] = request.session.get('count', 0) +1

    context = {
        # 'blogs': blogs,
        'count': request.session['count'],
        'object_list': page_object.object_list,
        'page_obj': page_object,
    }

    response =  render(request, 'blog_list.html', context)

    response.set_cookie('visits', visits)

    return response

    # templates 경로에 있을 시
    # return render(request, 'blog_list.html', context)
    # templates/blog 경로에 파일이 있을 시
    # return render(request, 'blog/blog_list.html', context)

def blog_detail(request, pk):
    # blog = Blog.objects.get(pk=pk)
    blog = get_object_or_404(Blog, pk=pk)
    context = {
        'blog':blog,
    }
    return render(request, 'blog_detail.html', context)

@login_required # settings.py에 설정된 LOGIN_URL로 리다이렉트
def blog_create(request):

    # 로그인되어 있지 않으면 로그인화면으로 리다이렉트
    # if not request.user.is_authenticated:
    #     return redirect(reverse('login'))

    # if request.method == 'POST':
    #     form = BlogForm(request.POST)
    #     if form.is_valid():
    #         blog = form.save() # form.save() : form에 내용을 DB에 반영하고 해당 데이터의 객체를 반환(리턴)함.
    #         return redirect(reverse('blog_detail'), {'pk':blog.pk})
    # else:
    #     form = BlogForm()

    form = BlogForm(request.POST or None)
    if form.is_valid():
        # form.save() : form에 내용을 DB에 반영하고 해당 데이터의 객체를 반환(리턴)함.
        blog = form.save(commit=False)  # DB에 반영하지 않고 객체만 반환함.
        blog.author = request.user  # 작성자에 로그인된 유저를 넣음
        blog.save()  # DB에 반영
        return redirect(reverse('fb:detail', kwargs={'pk':blog.pk}))

    context = {
        'form':form,
    }

    return render(request, 'blog_form.html', context)

@login_required
def blog_update(request, pk):
    # 관리자 접근 허용
    if request.user.is_superuser:
        blog = get_object_or_404(Blog, pk=pk)
    else:
        # blog = get_object_or_404(Blog, pk=pk)
        # if request.user != blog.author:
        #     raise Http404
        blog = get_object_or_404(Blog, pk=pk, author=request.user) # pk와 author가 일치하는 데이터만 가져옴

    # form = BlogForm(None, None, instance=blog)
    form = BlogForm(request.POST or None, request.FILES or None, instance=blog)  # instance 폼의 항목에 맞게 blog에서 데이터를 불러옴
    # print(request.POST) # POST요청시 들어오는 데이터를 볼 수 있음
    print(request.FILES) # 요청된 파일 목록을 기져옴.
    if form.is_valid():
        # print(form.cleaned_data)
        # form.save() : form에 내용을 DB에 반영하고 해당 데이터의 객체를 반환(리턴)함.
        blog = form.save()  # DB에 반영
        return redirect(reverse('fb:detail', kwargs={'pk':blog.pk}))

    context = {
        'blog':blog,
        'form':form,
   }

    return render(request, 'blog_form.html', context)


@login_required
@require_http_methods(['POST'])
def blog_delete(request, pk):
    # if request.method != 'POST':
    #     raise Http404

    blog = get_object_or_404(Blog, pk=pk, author=request.user) # pk와 author가 일치하는 데이터만 가져옴
    blog.delete()

    return redirect(reverse('fb:list'))

Django/05_blog_CBV/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>어바웃 페이지 입니다.</h1>
</body>
</html>

Django/05_blog_CBV/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>블로그 프로젝트</title>
{#    <link href="..static/css/bootstrap.css">#} {#    경로 바뀌면 안될 수도 있기 때문에 잘 안씀#}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <style>
        .page-link{
            color: gray;
        }
        .page-link:hover {
            color: black;
        }
        .page-link:active, .page-link:focus, input.form-control:focus {
            border-color: gray;
            box-shadow: 0 0 4px 1px gray;
            color: black;
        }
        .page-link.active {
            background-color: lightgray;
            color: white;
            border-color: gray;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
    <nav class="d-flex justify-content-between py-2 px-4 bg-black opacity-50 text-white">
        <div>
            <a class="btn btn-success" href="{% url 'blog:list' %}">홈</a>
        </div>
        <div style="text-align: right">
            {% if request.user.is_authenticated %}
            <form action="{% url 'logout' %}" method="POST" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-danger btn-sd">로그아웃</button>
            </form>
            {{ request.user.username }}
            {% else %}
            <a href="{% url 'signup' %}">회원가입</a>
            <a href="{% url 'login' %}">로그인</a>
            {% endif %}
        </div>
    </nav>
    <div class="container pt-5">
        {% block content %}{% endblock %}
    </div>
    <footer></footer>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

Django/05_blog_CBV/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div class="mt-2 d-flex justify-content-between">
            <h1>{{ blog.title }}</h1>
            {% if request.user == blog.author or request.user.is_superuser %}{# request.user.is_superuser 하거나 request.user.is_staff하면 관리자 허용 #}
            <div>
                <a class="btn btn-warning opacity-50" href="{% url 'blog:update' blog.pk %}">수정</a>
                <form action="{% url 'blog:delete' blog.pk %}" method="POST" id="delete_form" style="display:inline">
                    {% csrf_token %}
                    <button class="btn btn-danger opacity-50" type='button' id="delete_btn">삭제</button>
                </form>
            </div>
            {% endif %}
        </div>
        {% if blog.image %}
            <img src="{{ blog.image.url }}" alt="" class="w-100">
        {% endif %}
        <hr>
        <div>
{#            {{ blog.content }}#}
            {{ blog.content | safe }}  <!-- 써머노트 쓸 때 html코드를 사용할 수 있게 설정. -->
        </div>
        <hr>
        {% if request.user.is_authenticated %}
{#            <form method="post">#}
            <form method="post" action="{% url 'blog:comment-create' blog.pk %}">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <div class="text-end">
                    <button class="btn btn-primary opacity-50">댓글작성</button>
                </div>
            </form>
        {% endif %}
        <div class="mb-5" id="comment_wrapper">
{#            Django에서는 ForeignKey(외래 키) 관계가 설정되면, 역참조(Reverse Lookup)를 위한 관련 매니저가 자동으로 생성됩니다.#}
{#            즉, Comment 모델이 Blog 모델을 참조하고 있다면, Django는 자동으로 blog.comment_set이라는 매니저를 제공하여 해당 Blog 객체에 연결된 모든 Comment를 가져올 수 있도록 합니다.#}
{#            {% for comment in blog.comment_set.all %}#}
            {% for comment in object_list %}

                <div class="border-bottom">
                    {{ comment.content }}
                    <p class="text-end">
                        <small>{{ comment.created_at | date:'Y-m-d H:i' }} | {{ comment.author.username }}</small>
                    </p>
                </div>
            {% endfor %}
        </div>

        <div style="text-align: right;">
            <small>by {{ blog.author.username }}</small>
        </div>
        {%  include 'pagination.html' with fragment='comment_wrapper' %}
        <div style="text-align: center; margin: 50px 0;">
            <a class="btn btn-secondary opacity-50" href="{% url 'blog:list' %}">목록</a>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        document.querySelector('#delete_btn').addEventListener('click', function() {
            {#console.log('click');#}
            if(confirm('삭제 하시겠습니까?')){
                document.querySelector('#delete_form').submit();
            }
        })
    </script>
{% endblock %}

Django/05_blog_CBV/templates/blog_form.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-2">
    <form method="POST" enctype="multipart/form-data">
        <h1>블로그 {{ sub_title }}</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary opacity-50">{% if btn_name %}{{ btn_name }}{% else %}저장{% endif %}</button>
    </form>
</div>
{% endblock %}
{% block js %}
    {% include 'form_js.html' %}
{% endblock %}

Django/05_blog_CBV/templates/blog_list.html
{% extends 'base.html' %}
{% block css %}
{% endblock %}
{% block content %}
    <div>
        <div class="mt-2">
            <h1 class="d-inline">블로그 목록 {{ count }}</h1>
            <a class="btn btn-success opacity-50 float-end" href="{% url 'blog:create' %}">생성</a>
        </div>
        <hr>
        {% for blog in object_list %}
            <div class="my-3">
                <a class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover" href="{% url 'blog:detail' blog.pk %}">
                    {% if blog.get_thumbnail_image_url %}
                        <img src="{{ blog.get_thumbnail_image_url }}" alt="" class="col-2">
                    {% endif %}

{#                    {% if blog.thumbnail %}#}
{#                        <img src="{{ blog.thumbnail.url }}" alt="" class="col-2">#}
{#                    {% endif %}#}
{#                    {% if blog.image %}#}
{#                        <img src="{{ blog.image.url }}" alt="" class="col-2">#}
{#                    {% endif %}#}
                    <sapn class="col-10">
                        [{{ blog.get_category_display }}] ({{ blog.id }}) {{ blog.title }} <small>by {{ blog.author.username }}</small> - <small>{{ blog.created_at | date:"Y-m-d"}}</small>
                    </sapn>
                </a>
            </div>
        {% endfor %}
        <form method="get">
            <div class="my-4 d-flex justify-content-center">
                <div style="width: 400px;">
                    <input class="form-control" name="q" type="text" placeholder="검색어를 입력하세요." value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">
                </div>
                <button class="btn btn-secondary opacity-50">검색</button>
            </div>
        </form>
{#        페이지네이션#}
        {%  include 'pagination.html' %}
    </div>
{% endblock %}

Django/05_blog_CBV/templates/form_js.html
<script>
    document.querySelectorAll('select, input, textarea').forEach(function(ele) {
        ele.classList.add('form-control')
    });
</script>

Django/05_blog_CBV/templates/pagination.html
<div class="text-align-center d-flex justify-content-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}  {# 이전 페이지 존재시 #}
                    <li class="page-item">
                        <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">&laquo; 첫번째</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">이전</a></li>
                {% endif %}

                {# 총 페이지 중에 현재 몇 페이지인지 표시 #}
                {# <span> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} </span> #}

                {# 현재페이지 -2 > 1 이면 ... #}
                {% if page_obj.number|add:-2 > 1 %}
                    <il class="page-item">
                        <a class="page-link" href="?page={{ page_obj.number|add:-3 }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">&hellip;</a>
                    </il>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <il class="page-item">
                            <a class="page-link active" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">{{ i }}</a>
                        </il>
                    {# 현재페이지 - 2 <= 현재페이지 <= 현재페이지 + 2 #}
                    {% elif page_obj.number|add:-2 <= i and i <= page_obj.number|add:2 %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {# 최대페이지 > 현재페이지 + 2 이면 ... #}
                {% if page_obj.paginator.num_pages > page_obj.number|add:2 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.number|add:3 }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">&hellip;</a>
                    </li>
                {% endif %}

                {% if page_obj.has_next %} {# 다음 페이지 존재시 #}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">다음</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment %}#{{ fragment }}{% endif %}">마지막 &raquo;</a>
                    </li>
                {% endif %}
            </ul>
        </div>

Django/05_blog_CBV/templates/test_get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>TEST GET</h1>
    <form method="POST">
        {% csrf_token %}
        <button>TO POST</button>
    </form>
</body>
</html>

Django/05_blog_CBV/templates/test_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>TEST POST</h1>
</body>
</html>